/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jprojectorcontrol.gui;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import jprojectorcontrol.projectors.ProjectorModels;
import org.apache.log4j.Logger;

/**
 *
 * @author martijncourteaux
 */
public class OverviewFrame extends javax.swing.JFrame
{

    private ProjectorManager man;
    private File projectorFile;

    /**
     * Creates new form OverviewFrame
     */
    public OverviewFrame()
    {
        man = new ProjectorManager();
        projectorFile = new File("proj.txt");
        if (projectorFile.exists())
        {
            try
            {
                man.load(projectorFile);
            } catch (IOException ex)
            {
                Logger.getLogger("UI").error(null, ex);
            }
        }

        initComponents();
        treeProjectors.setModel(man.createTreeModel(true));
        treeProjectors.setCellRenderer(new ProjectorTreeRenderer());

        cmbModel.setModel(ProjectorModels.createComboBoxModel());
        cmbModel.setRenderer(new ModelListRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        treeProjectors = new javax.swing.JTree();
        btnManageProjectors = new javax.swing.JButton();
        pnlGeneral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fldHostPort = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbModel = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        fldLocation = new javax.swing.JTextField();
        scroller = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JProjectorControl");

        treeProjectors.setRootVisible(false);
        jScrollPane1.setViewportView(treeProjectors);

        btnManageProjectors.setText("Manage Projectors");
        btnManageProjectors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProjectorsActionPerformed(evt);
            }
        });

        pnlGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));

        jLabel1.setText("Host/Port:");

        fldHostPort.setEditable(false);
        fldHostPort.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        jLabel2.setText("Model:");

        cmbModel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hitachi CPX2" }));

        jLabel3.setText("Location:");

        org.jdesktop.layout.GroupLayout pnlGeneralLayout = new org.jdesktop.layout.GroupLayout(pnlGeneral);
        pnlGeneral.setLayout(pnlGeneralLayout);
        pnlGeneralLayout.setHorizontalGroup(
            pnlGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(pnlGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(cmbModel, 0, 272, Short.MAX_VALUE)
                    .add(fldLocation)
                    .add(fldHostPort))
                .addContainerGap())
        );
        pnlGeneralLayout.setVerticalGroup(
            pnlGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlGeneralLayout.createSequentialGroup()
                .add(pnlGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(fldHostPort, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(cmbModel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlGeneralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(fldLocation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .add(btnManageProjectors, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlGeneral, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(scroller, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(pnlGeneral, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(scroller, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnManageProjectors)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageProjectorsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnManageProjectorsActionPerformed
    {//GEN-HEADEREND:event_btnManageProjectorsActionPerformed
        ProjectorManagerFrame f = new ProjectorManagerFrame(this, man);
        f.setVisible(true);
        treeProjectors.setModel(man.createTreeModel(true));
        try
        {
            man.save(projectorFile);
        } catch (IOException ex)
        {
            Logger.getLogger("UI").error(null, ex);
        }

    }//GEN-LAST:event_btnManageProjectorsActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageProjectors;
    private javax.swing.JComboBox cmbModel;
    private javax.swing.JTextField fldHostPort;
    private javax.swing.JTextField fldLocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlGeneral;
    private javax.swing.JScrollPane scroller;
    private javax.swing.JTree treeProjectors;
    // End of variables declaration//GEN-END:variables
}
